name: Auto Contributions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run your action
      uses: ./path-to-your-action

  generate:
    runs-on: ubuntu-latest
    name: Generate 3D Profile SVGs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run local action
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push
        run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com
          git add .
          git commit -m "Updated 3D Profile SVGs."
          git push
