name: WakaTime status update

on:
  schedule:
    # Runs at 12:01 AM UTC every day
    - cron: "1 0 * * *"

jobs:
  update-readme:
    name: Update the WakaTime Stat
    runs-on: ubuntu-latest
    steps:
      - uses: avinal/Profile-Readme-WakaTime@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GITHUB_TOKEN: ${{ github.token }}
          BRANCH: "master"  # or "main" depending on your repo's default branch
          COMMIT_MSG: "Automated Coding Activity Update :alien:"
          STATS_RANGE: "last_30_days"
